#!/bin/bash

n="$(printf '\033[0m')"
R="$(printf '\033[1;31m')"                                                                                G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"                                                                                W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"

pkgs=($@)

for pkg in "${pkgs[@]}"; do
        type -p "$pkg" &>/dev/null || {
                echo -e "\n${R} [${G} ● ${R}]${G} Installing package : ${Y} $pkg ${C}\n"
                sudo apt install "$pkg" -y --no-install-recommends
                echo -e "\n\t${R}● ${Y}${pkg}${G} INSTALLATION COMPLETED ${R}●\n"${n}
        }
done
echo -e "\n\t${R}● ${C}[ ${Y}${pkgs[@]} ${C}] ${G}Done ! 🤘 ${R}●\n"${n}
