#!/bin/bash

R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"

packs=($@)

INSTALL(){
	for pkgs in "${packs[@]}"; do
		type -p "$pkgs" &>/dev/null || {
			echo -e "\n${R} [${G} ● ${R}]${G} Installing package : ${Y} $pkgs ${C}\n"
			sudo apt install "$pkgs" -y --no-install-recommends
			echo -e "\n\t${R}● ${Y}${pkgs} ${G}INSTALLATION COMPLETED ${R}●\n"${W}
		}
	done
#	echo -e "\n\t${R}● ${Y}${packs[@]} ${G}INSTALLATION COMPLETED ${R}●\n"${W}
}
INSTALL
